/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Farisya
 */
public class inpengolahan extends javax.swing.JFrame {

    /**
     * Creates new form inpengolahan
     */
    public inpengolahan() {
        initComponents();
    }

    public void klikKembali(ActionListener a) {
        this.back.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        susu1 = new javax.swing.JLabel();
        gula1 = new javax.swing.JLabel();
        pisang1 = new javax.swing.JLabel();
        susu3 = new javax.swing.JLabel();
        gula3 = new javax.swing.JLabel();
        melon = new javax.swing.JLabel();
        susu2 = new javax.swing.JLabel();
        gula2 = new javax.swing.JLabel();
        semangka = new javax.swing.JLabel();
        susu4 = new javax.swing.JLabel();
        mangga1 = new javax.swing.JLabel();
        gula4 = new javax.swing.JLabel();
        susu5 = new javax.swing.JLabel();
        gula5 = new javax.swing.JLabel();
        apel1 = new javax.swing.JLabel();
        apel2 = new javax.swing.JLabel();
        minyak1 = new javax.swing.JLabel();
        pisang2 = new javax.swing.JLabel();
        minyak2 = new javax.swing.JLabel();
        minyak3 = new javax.swing.JLabel();
        mangga2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui export/back.png"))); // NOI18N
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, -1, -1));

        susu1.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        susu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        susu1.setText("0");
        getContentPane().add(susu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 40, 30));

        gula1.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        gula1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gula1.setText("0");
        getContentPane().add(gula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 30, 30));

        pisang1.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        pisang1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pisang1.setText("0");
        getContentPane().add(pisang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 40, 30));

        susu3.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        susu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        susu3.setText("0");
        getContentPane().add(susu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 40, 30));

        gula3.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        gula3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gula3.setText("0");
        getContentPane().add(gula3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 40, 30));

        melon.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        melon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        melon.setText("0");
        getContentPane().add(melon, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 40, 30));

        susu2.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        susu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        susu2.setText("0");
        getContentPane().add(susu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 40, 30));

        gula2.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        gula2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gula2.setText("0");
        getContentPane().add(gula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 40, 40));

        semangka.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        semangka.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        semangka.setText("0");
        getContentPane().add(semangka, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 414, 40, 30));

        susu4.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        susu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        susu4.setText("0");
        getContentPane().add(susu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 40, 30));

        mangga1.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        mangga1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mangga1.setText("0");
        getContentPane().add(mangga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 40, 30));

        gula4.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        gula4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gula4.setText("0");
        getContentPane().add(gula4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 40, 30));

        susu5.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        susu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        susu5.setText("0");
        getContentPane().add(susu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, 40, 30));

        gula5.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        gula5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gula5.setText("0");
        getContentPane().add(gula5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 170, 40, 30));

        apel1.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        apel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apel1.setText("0");
        getContentPane().add(apel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 40, 40));

        apel2.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        apel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apel2.setText("0");
        getContentPane().add(apel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 340, 40, 30));

        minyak1.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        minyak1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minyak1.setText("0");
        getContentPane().add(minyak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 410, 40, 30));

        pisang2.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        pisang2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pisang2.setText("0");
        getContentPane().add(pisang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 560, 50, 30));

        minyak2.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        minyak2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minyak2.setText("0");
        getContentPane().add(minyak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 630, 50, 30));

        minyak3.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        minyak3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minyak3.setText("0");
        getContentPane().add(minyak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 30, 30));

        mangga2.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        mangga2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mangga2.setText("0");
        getContentPane().add(mangga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, 50, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui export/inpengolahan.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        ImageIcon awal = new ImageIcon(getClass().getResource("/ui export/backhover.png"));
        back.setIcon(awal); // TODO add your handling code here:
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        ImageIcon awal = new ImageIcon(getClass().getResource("/ui export/back.png"));
        back.setIcon(awal);        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inpengolahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inpengolahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inpengolahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inpengolahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inpengolahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apel1;
    private javax.swing.JLabel apel2;
    private javax.swing.JButton back;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel gula1;
    private javax.swing.JLabel gula2;
    private javax.swing.JLabel gula3;
    private javax.swing.JLabel gula4;
    private javax.swing.JLabel gula5;
    private javax.swing.JLabel mangga1;
    private javax.swing.JLabel mangga2;
    private javax.swing.JLabel melon;
    private javax.swing.JLabel minyak1;
    private javax.swing.JLabel minyak2;
    private javax.swing.JLabel minyak3;
    private javax.swing.JLabel pisang1;
    private javax.swing.JLabel pisang2;
    private javax.swing.JLabel semangka;
    private javax.swing.JLabel susu1;
    private javax.swing.JLabel susu2;
    private javax.swing.JLabel susu3;
    private javax.swing.JLabel susu4;
    private javax.swing.JLabel susu5;
    // End of variables declaration//GEN-END:variables
}
