/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Farisya
 */
public class popup_s extends javax.swing.JFrame {

    /**
     * Creates new form popup_s
     */
    public popup_s() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public JLabel setGambar() {
        return bahan;
    }

    public void tombolTambah(ActionListener action) {
        this.add.addActionListener(action);
    }

    public void tombolMin(ActionListener action) {
        this.min.addActionListener(action);
    }

    public void tombolBeli(ActionListener action) {
        this.beli.addActionListener(action);
    }

    public void tombolBatal(ActionListener action) {
        this.batal.addActionListener(action);
    }

    public int getTeksJumlah() {
        String hasil = jml.getText();
        return Integer.valueOf(hasil);
    }

    public void setTeksJumlah(String teks) {
        jml.setText(teks);
    }

    public void tampilPesan(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bahan = new javax.swing.JLabel();
        beli = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        add = new javax.swing.JButton();
        min = new javax.swing.JButton();
        jml = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bahan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui export/tepung.png"))); // NOI18N
        getContentPane().add(bahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 100));

        beli.setBorder(null);
        beli.setBorderPainted(false);
        beli.setContentAreaFilled(false);
        beli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 160, 80));

        batal.setBorder(null);
        batal.setBorderPainted(false);
        batal.setContentAreaFilled(false);
        batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 160, 80));

        add.setBorder(null);
        add.setBorderPainted(false);
        add.setContentAreaFilled(false);
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 60, 70));

        min.setBorder(null);
        min.setBorderPainted(false);
        min.setContentAreaFilled(false);
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 70, 70));

        jml.setFont(new java.awt.Font("DFPOP1-W9", 0, 36)); // NOI18N
        jml.setText("1");
        getContentPane().add(jml, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 50, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui export/popupsupermarket.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popup_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popup_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popup_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popup_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popup_s().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel bahan;
    private javax.swing.JButton batal;
    private javax.swing.JButton beli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jml;
    public javax.swing.JButton min;
    // End of variables declaration//GEN-END:variables

}
